version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'mysql_user' #?
      MYSQL_PASSWORD: 'mysql_password' #?
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: